site_name: Wheke
site_url: https://wheke.humberto.io/
site_author: Humberto Rocha
site_description: A cute framework for small self-hosted apps

repo_url: https://github.com/humrochagf/wheke

nav:
  - Introduction: index.md
  - Pods: pods.md
  - API Docs: api.md

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            separate_signature: true
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
